version: '3.8'

services:

#docker run -dp 3000:3000 --network todo-app -e MYSQL_HOST=mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=secret -e MYSQL_DB=todos getting-started:v2
    app:
        image: nodeapp
        build: .
        ports: 
            - 3000:3000
        #Lugar donde estan los archivos de la web *arranca con ./nameVol:/directorioApp    
        volumes:
            - ./app:/app
        environment:
            MYSQL_HOTS: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: docker_test


# docker run -d     --network todo-app --network-alias mysql     -v todo-mysql-data:/var/lib/mysql     -e MYSQL_ROOT_PASSWORD=secret     -e MYSQL_DATABASE=todos     mysql:5.7
    mysql:
        image: mysql:5.7
        ports:
            - 3307:3306
        #Lugar donde se guardan los datos de la BD *arranca con nameVol:/directorioMYSQL
        volumes: 
            - app:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: docker_test 

volumes:
    app: